# Generated by Django 5.2.17 on 2026-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Identificador público del insumo, ej: INS-00458', max_length=40, unique=True)),
                ('nombre_tecnico', models.CharField(max_length=200)),
                ('cantidad_disponible', models.PositiveIntegerField(help_text='Cantidad actual en stock, en la unidad de medida del insumo')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: kg, litros, unidades, ampollas', max_length=20)),
                ('umbral_stock_bajo', models.PositiveIntegerField(help_text='Cantidad mínima operativa. Por debajo de este valor, el insumo se considera en stock bajo (salvo que ya esté vencido).')),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo crítico',
                'verbose_name_plural': 'Insumos críticos',
                'ordering': ['fecha_vencimiento'],
                'indexes': [models.Index(fields=['fecha_vencimiento'], name='core_insumo_fecha_v_aeddcc_idx'), models.Index(fields=['identificador'], name='core_insumo_identif_9f698e_idx')],
            },
        ),
    ]
